name: Build and Deploy WASM

on: workflow_dispatch
permissions:
  contents: write  # Allows to commit files 

jobs:
  build-and-update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
      - name: Initialize submodules manually
        run: git submodule update --init --recursive
      - name: Compile C++ to WASM
        run: |
          emcc -x c++ firmware/newmain/my-lib/examples/includeAll.c -o vason_parser.js --bind -s ALLOW_MEMORY_GROWTH=1 -DnoAssertMessage -O3 -s WASM_ASYNC_COMPILATION=0
      - name: Copy files to docs folder
        run: |
          mkdir -p docs/vason_wasm
          cp vason_parser.js docs/vason_wasm/
          cp vason_parser.wasm docs/vason_wasm/
          cp vason.js docs/vason_wasm/

      - name: Commit and Push to GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/vason_wasm/
          
          # This checks if the compiled files actually changed before trying to commit
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-compile WASM and update docs" && git push)
