name: Build and Deploy to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14

      - name: Initialize wheels
        run: git clone https://github.com/mintoya/wheels firmware/newmain/my-lib

      - name: Compile C++ to WASM
        run: |
          # -s SINGLE_FILE=1 bundles the WASM into the JS file
          emcc -x c++ firmware/newmain/my-lib/examples/includeAll.c \
            -o vason_parser.js                                      \
            --bind                                                  \
            -DnoAssertMessage                                       \
            -O3                                                     \
            -s ALLOW_MEMORY_GROWTH=1                                \
            -s WASM_ASYNC_COMPILATION=0                             \
            -s EXPORT_ES6=1                                         \
            -s MODULARIZE=1                                         \
            -s SINGLE_FILE=1

      - name: Move to docs
        run: |
          mkdir -p docs/vason_wasm
          mv vason_parser.js docs/vason_wasm/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  deploy:
    if: github.actor != 'nektos/act' 
    needs: build-wasm
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
